name: device_name
description: A Flutter package for getting device name from device identifier.
version: 0.0.3
homepage: https://github.com/edasandesu/device_name

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
