name: device_name
description: A Flutter package for getting device name from device identifier.
version: 0.0.2
homepage: https://github.com/edasandesu/device_name

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
